# Generated by Django 5.2.8 on 2025-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rollno", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=25)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "COMPUTER SCIENCE ENGINEERING"),
                            ("IT", "INFORMATION TECHNOLOGY"),
                            ("EE", "ELECTRICAL ENGINEERING"),
                        ]
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
            ],
        ),
    ]
